modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AyameMC/Ayame-PaperDoll/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "ayame_paperdoll"
version = "${version}"
displayName = "Ayame PaperDoll"
displayURL = "https://github.com/AyameMC/Ayame-PaperDoll"
authors = '''
LucunJi(Original author)
HappyRespawnanchor
'''
credits = '''
Fallen_Breath
X-Green
altrisi
plusls
HappyRespawnanchor(Port to Architectury)
pertaz(Port to Architectury)
'''
description = '''
Highly configurable PaperDoll mod.
Fork from Extra Player Renderer.
'''
logoFile = "icon.png"
updateJSONURL = "https://updatechecker.ayamemc.org/neoforge/ayame-paperdoll/update.json"
[[dependencies.ayame_paperdoll]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ayame_paperdoll]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ayame-paperdoll.mixins.json"
