modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AyameMC/PaperDoll-Renderer/issues"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "paperdollrender"
version = "${version}"
displayName = "PaperDoll Render"
displayURL = "https://github.com/AyameMC/PaperDoll-Renderer"
authors = '''
LucunJi(Original author)
HappyRespawnanchor
pertaz(Port to Architectury)
'''
credits = '''
Fallen_Breath
X-Green
altrisi
plusls
HappyRespawnanchor
pertaz(Port to Architectury)
'''
description = '''
Render an extra player figure on your screen. Made for game streaming and recordings. Well integrated with Ayame.
'''
logoFile = "paperdollrender_logo.png"
updateJSONURL = "https://updatechecker.ayamemc.org/neoforge/paperdollrender/update.json"
[[dependencies.paperdollrender]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.paperdollrender]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "paperdollrender.mixins.json"
