name: Quick Fabric Release
on:
  push:
    tags:
      - '*-*'
env:
  JAVA_VERSION: 21 # must be the same as the version used in build.gradle
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradlew
        run: |
          chmod +x ./gradlew
          ./gradlew configureLaunch
      - name: Check Version
        run: |
          __version="$(./gradlew -q properties --property version | grep version: | sed -r 's/version:\s*//')"
          if [ "$__version" == "${{ github.ref_name }}" ]
          then
            echo "OK: version and tag matches"
          else
            echo "ERR: version ${__version} and tag (${{ github.ref_name }}) does not match"
            exit 1
          fi

  build-release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build
        id: build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 7q8r8AtY
          modrinth-token: ${{ secrets.MODRINTH_AUTHORIZATION_TOKEN }}
          curseforge-id: 372888
          curseforge-token: ${{ secrets.CURSEFORGE_UPLOAD_TOKEN }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          java: ${{ env.JAVA_VERSION }}
          version: ${{ steps.build.outputs.version }}
          game-versions: ${{ steps.build.outputs.game_versions }}
          files: ${{ steps.build.outputs.files }}
          name: ${{ steps.build.outputs.release_name }}

          github-tag: ${{ github.ref_name }}