name: Publish Release Artifacts

on:
  release:
    types: [ created ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6


      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Mod
        run: sh build.sh


      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.tag_name }} 更新
          body: 发布 ${{ github.event.release.tag_name }}
          files: |
            result/*
          generate_notes: true
